In [1]:
import numpy as np

In [2]:
#THEORETICAL QUESTIONS 
# Q1 Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?


#NumPy, short for "Numerical Python," is a fundamental package in Python that greatly enhances its capabilities for scientific computing and data analysis. Its purpose is to provide an efficient way to work with arrays and matrices, as well as a vast library of mathematical functions to operate on these data structures.
#It enhance it by:
#Efficient array computations and speed and performance.
#Mathematical and statistical functions and data cleaning and transformation.
#Community and ecosystem.

In [3]:
# Q2 Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


#In NumPy, both `np.mean()` and `np.average()` calculate the average of an array, but they differ in functionality and flexibility. `np.mean()` calculates the arithmetic mean of an array along a specified axis, giving equal weight to each element, and is simpler to use when all values contribute equally. In contrast, `np.average()` allows for optional weighting of elements, where a `weights` parameter can assign different importance to each value, making it useful when some data points should have more influence in the average. If you need a straightforward mean, `np.mean()` is ideal, but if the context requires weighted data (e.g., in surveys or experiments with varying significance of data points), `np.average()` provides the needed flexibility.

In [4]:
#Q3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

# To reverse a NumPy array along different axes, slicing with negative steps (`[::-1]`) is a common method. For a 1D array, reversing can be done simply with `arr[::-1]`, which inverts the order of elements. For 2D arrays, reversing along rows is achieved with `arr[::-1, :]`, flipping the order of rows, while reversing along columns is done with `arr[:, ::-1]`, flipping the order of columns. To reverse both dimensions, use `arr[::-1, ::-1]`, which will invert both rows and columns. For example, if `arr = np.array([1, 2, 3])`, `arr[::-1]` results in `[3, 2, 1]`. For a 2D array `arr = np.array([[1, 2], [3, 4]])`, `arr[::-1, :]` gives `[[3, 4], [1, 2]]` and `arr[:, ::-1]` results in `[[2, 1], [4, 3]]`.

In [5]:
# Q4 How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.


# To determine the data type of elements in a NumPy array, you can use the `dtype` attribute, accessed with `array.dtype`. This reveals the specific data type (e.g., `int32`, `float64`) of the array’s elements. Understanding data types in NumPy is crucial for memory management and performance because each data type occupies a specific amount of memory. For instance, an `int32` type uses 4 bytes per element, while `float64` uses 8 bytes, meaning that larger data types increase memory consumption. By selecting an appropriate data type based on data precision needs, you can minimize memory usage, which is especially important for large datasets. Additionally, using simpler data types like `int32` or `float32` over `float64` can speed up computations, as operations on smaller data types are generally faster. Effective data type selection allows NumPy to handle large data efficiently, contributing to optimized performance in scientific and data-intensive applications.

In [6]:
# Q5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

# In NumPy, `ndarray` (n-dimensional array) is a powerful data structure used for storing and manipulating homogeneous, multi-dimensional data. Unlike standard Python lists, which can contain mixed data types and are limited in performance, `ndarrays` store elements of the same data type in a contiguous block of memory, allowing for faster access and efficient mathematical operations. Key features of `ndarrays` include support for multi-dimensional arrays (1D, 2D, and beyond), efficient broadcasting capabilities (where smaller arrays are expanded to match larger arrays for element-wise operations), and an extensive library of mathematical functions optimized for these arrays. Additionally, `ndarrays` offer slicing, indexing, and reshaping capabilities that enable complex data manipulations with concise code. This design allows `ndarrays` to be highly performant for numerical computations compared to Python lists, which are not optimized for such operations and lack advanced array-handling features like broadcasting.

In [7]:
# Q6  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.


# NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to their memory efficiency and computational optimizations. Unlike Python lists, which store elements as individual Python objects with additional overhead, NumPy arrays store data in a compact, contiguous memory block, allowing for faster access and less memory usage. This structure enables efficient element-wise operations without the need for looping through each element, as NumPy leverages low-level C and Fortran libraries that are optimized for vectorized operations. As a result, mathematical operations on NumPy arrays can be performed much faster than on Python lists, especially when handling large datasets. Additionally, NumPy arrays support broadcasting, which allows operations to be applied across different array shapes without extra copying, further reducing the computational load. These advantages make NumPy arrays ideal for tasks in data analysis, machine learning, and scientific computing, where performance and memory efficiency are critical.

In [8]:
# Q7 Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

# In NumPy, vstack() and hstack() are used to stack arrays vertically and horizontally, respectively. vstack() (vertical stack) combines arrays along rows (axis 0), stacking them one on top of the other, while hstack() (horizontal stack) combines arrays along columns (axis 1), joining them side-by-side.

a = np.array([1, 2])
b = np.array([3, 4])
np.vstack((a, b))


a = np.array([1, 2])
b = np.array([3, 4])
np.hstack((a, b))


array([1, 2, 3, 4])

In [9]:
a = np.array([1, 2])
b = np.array([3, 4])
np.vstack((a, b))


array([[1, 2],
       [3, 4]])

In [10]:
# Q8  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

# fliplr() (flip left-right) reverses the order of columns in a 2D array or higher along the horizontal axis (axis 1). It is commonly used for 2D arrays to create a mirror image along the vertical axis.
# flipud() (flip up-down) reverses the order of rows in a 2D array or higher along the vertical axis (axis 0), creating a mirror image along the horizontal axis.

arr = np.array([[1, 2], [3, 4]])
np.fliplr(arr)

array([[2, 1],
       [4, 3]])

In [11]:
arr = np.array([[1, 2], [3, 4]])
np.flipud(arr)

array([[3, 4],
       [1, 2]])

In [12]:
# Q9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?


# The array_split() method in NumPy splits an array into specified sub-arrays along a given axis. Unlike split(), which requires equal-sized splits, array_split() can handle uneven splits by dividing the array as evenly as possible. If the array cannot be divided equally, some of the resulting sub-arrays will have one more element than others.
arr = np.array([1, 2, 3, 4, 5])
np.array_split(arr, 3)

[array([1, 2]), array([3, 4]), array([5])]

In [13]:
# Q10 Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

#Vectorization is the process of applying operations directly on entire arrays rather than on individual elements, making use of low-level optimizations and avoiding Python loops. For example, adding two arrays element-wise (a + b) is vectorized, allowing the operation to be executed much faster than looping through each element. This reduces computational overhead and improves speed, especially for large arrays.
#Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" the smaller array to match the shape of the larger array, without creating extra copies. For instance, if you add a 1D array to a 2D array, NumPy broadcasts the 1D array across the 2D array’s rows or columns. Broadcasting makes array operations more flexible and avoids the need for reshaping or looping over dimensions manually.

In [14]:
# PRACTICAL QUESTIONS 


In [15]:
import random

In [16]:
# Q1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

arr=np.random.randint(1,100,size=(3,3))
arr

array([[97, 61, 15],
       [93,  6,  4],
       [40, 50, 96]])

In [17]:
arr.T

array([[97, 93, 40],
       [61,  6, 50],
       [15,  4, 96]])

In [18]:
# Q2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

arr2=np.array([2,6,44,98,23,16,38,45,68,53])
arr2

array([ 2,  6, 44, 98, 23, 16, 38, 45, 68, 53])

In [19]:
arr2.reshape(2,5)

array([[ 2,  6, 44, 98, 23],
       [16, 38, 45, 68, 53]])

In [20]:
arr2.reshape(5,2)

array([[ 2,  6],
       [44, 98],
       [23, 16],
       [38, 45],
       [68, 53]])

In [21]:
# Q3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

arr3= np.random.rand(4, 4)
arr4= np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

In [24]:
arr3= np.random.rand(4, 4)

In [25]:
arr3

array([[0.58862135, 0.27557969, 0.67197926, 0.71420839],
       [0.98914454, 0.33360444, 0.95721595, 0.21827523],
       [0.79467023, 0.96653974, 0.77962391, 0.62581315],
       [0.44045361, 0.23690809, 0.20276984, 0.99640048]])

In [26]:
arr4= np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

In [27]:
arr4

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.12835873, 0.55048199, 0.08644895, 0.64485321,
        0.        ],
       [0.        , 0.28682045, 0.92156317, 0.62447478, 0.83617241,
        0.        ],
       [0.        , 0.11413968, 0.42670187, 0.93627205, 0.77705477,
        0.        ],
       [0.        , 0.08757671, 0.09852203, 0.67758435, 0.34323202,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [28]:
# Q4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.

arr=np.arange(10,60,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [29]:
# Q5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.


arr=np.array(['python','numpy','pandas'])
arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [32]:
ar1=np.char.upper(arr)
ar1

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [33]:
ar2=np.char.lower(arr)
ar2

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [34]:
ar3=np.char.capitalize(arr)
ar3

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [35]:
ar4=np.char.title(arr)
ar4

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [36]:
# Q6 Generate a NumPy array of words. Insert a space between each character of every word in the array.


words_array = np.array(['hello', 'world', 'numpy', 'array'])

spaced_words_array = np.char.join(' ', words_array)

print(spaced_words_array)


['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


In [37]:
# Q7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([[7,8],[9,10],[11,12]])


In [38]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
arr2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [40]:
arr1+arr2

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [41]:
arr1-arr2

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [42]:
arr1*arr2

array([[ 7, 16],
       [27, 40],
       [55, 72]])

In [43]:
arr1/arr2

array([[0.14285714, 0.25      ],
       [0.33333333, 0.4       ],
       [0.45454545, 0.5       ]])

In [44]:
# Q8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

arr1=np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
np.diag(arr1) #Extraction of diagonal elements

array([1., 1., 1., 1., 1.])

In [49]:
# Q9 Q9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
random_integers = np.random.randint(0, 1001, size=100)

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

prime_numbers = np.array([num for num in random_integers if is_prime(num)])


print("Random Integers:")
print(random_integers)

print("\nPrime Numbers:")
print(prime_numbers)


Random Integers:
[ 65 106 758 568 460 791 607 462 445 627 330 556 293 156 751 802 856 548
 465 343 213 438 400 436 995 993 547 175  24 496 815 482 842 605 458 318
 858 689 254 857 197 602 185 825 840 512 527  89 760 780 634  33 564 852
 959 250 503 608 854 586 731 101 523 482 337 329 605 580 294 635 721 610
 810 630  59 678 947 708  13  19 720 564 992 391 314 347 548 959  46 770
 895 180 488  44 918 554 717 731 831 485]

Prime Numbers:
[607 293 751 547 857 197  89 503 101 523 337  59 947  13  19 347]


In [50]:
# Q10 Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

arr=np.random.randint(15,45,size=(4,7))
arr

array([[21, 36, 28, 22, 24, 37, 40],
       [18, 30, 27, 27, 42, 37, 39],
       [37, 37, 31, 29, 28, 34, 24],
       [44, 21, 16, 18, 35, 22, 25]])

In [52]:
arr1=np.mean(arr, axis=0)
arr1

array([30.  , 31.  , 25.5 , 24.  , 32.25, 32.5 , 32.  ])