In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
#Q1 Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each method and the final output after each method.

#method1

arr=np.array([[1,0,0],[0,1,0],[0,0,1]])

#method2

arr1=np.eye(3)

#method3

arr2=np.identity(3)

print(arr)
print(arr1)
print(arr2)



[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
#Q2 Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and Reshape that 1D array into a 2D array.

arr=np.linspace(1,10,100)
print(arr)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [5]:
arr.reshape(100,1)

array([[ 1.        ],
       [ 1.09090909],
       [ 1.18181818],
       [ 1.27272727],
       [ 1.36363636],
       [ 1.45454545],
       [ 1.54545455],
       [ 1.63636364],
       [ 1.72727273],
       [ 1.81818182],
       [ 1.90909091],
       [ 2.        ],
       [ 2.09090909],
       [ 2.18181818],
       [ 2.27272727],
       [ 2.36363636],
       [ 2.45454545],
       [ 2.54545455],
       [ 2.63636364],
       [ 2.72727273],
       [ 2.81818182],
       [ 2.90909091],
       [ 3.        ],
       [ 3.09090909],
       [ 3.18181818],
       [ 3.27272727],
       [ 3.36363636],
       [ 3.45454545],
       [ 3.54545455],
       [ 3.63636364],
       [ 3.72727273],
       [ 3.81818182],
       [ 3.90909091],
       [ 4.        ],
       [ 4.09090909],
       [ 4.18181818],
       [ 4.27272727],
       [ 4.36363636],
       [ 4.45454545],
       [ 4.54545455],
       [ 4.63636364],
       [ 4.72727273],
       [ 4.81818182],
       [ 4.90909091],
       [ 5.        ],
       [ 5

In [6]:
arr.reshape(1,100)

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
         1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
         1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
         2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
         2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
         3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
         3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
         4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
         4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
         5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
         5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
         6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
         6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
         6.90909091,  7.        ,  7.09090909,  7.1

In [7]:
#Q3 Explain the following terms:
#1 The difference in np.array, np.asarray and np.asanyarray.
#2 The difference between Deep copy and shallow copy.

#1 np.array: Always creates a copy, even if the input is already an ndarray.
#np.asarray: Creates a copy only if necessary (e.g., if the input is not an ndarray). It does not preserve subclasses.
#np.asanyarray: Avoids creating a copy if possible and preserves the subtype if the input is an ndarray subclass.

#2 Shallow copy is in which change occurs in both original and derived array whereas in deep copy only derived array got changed not the original one.


In [15]:
#Q4 Generate a 3x3 array with random floating-point numbers between 5 and 20. Then, round each number in the array to 2 decimal places.

arr=np.random.uniform(5,20,(3,3))
print(arr)
arr.round(2)

[[ 5.69933867  7.94543509  9.13821239]
 [ 5.07755035 10.67434288 11.63767224]
 [15.79464265 14.15238541  8.64260658]]


array([[ 5.7 ,  7.95,  9.14],
       [ 5.08, 10.67, 11.64],
       [15.79, 14.15,  8.64]])

In [18]:
#Q5 Create a NumPy array with random integers between 1 and 10 of shape (5, 6). After creating the array perform the following operations:

 #a)Extract all even integers from array.

 #b)Extract all odd integers from array.

arr=np.random.randint(1,10,(5,6))
arr

#a)
arr1=arr[arr%2==0]
arr1

#b)
arr2=arr[arr%2!=0]
arr2



array([[False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False]])

In [24]:
arr

array([[3, 1, 1, 9, 2, 8],
       [2, 2, 3, 6, 8, 6],
       [4, 3, 9, 2, 3, 7],
       [9, 1, 5, 7, 8, 5],
       [1, 1, 6, 2, 9, 4]])

In [27]:
arr1

array([[ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True]])

In [28]:
arr2

array([[False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False]])

In [35]:
#Q6 Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10. Perform the following operations:

 #a) Find the indices of the maximum values along each depth level (third axis).

 #b) Perform element-wise multiplication of between both array.

arr=np.arange(24).reshape(2,3,4)
arr

arr1=np.arange(24).reshape(1,4,6)
arr1

#a)
indices=np.argmax(arr,axis=2)
indices

#b)
x=arr*arr1.reshape(2,3,4)

In [36]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
x

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]])

In [38]:
indices

array([[3, 3, 3],
       [3, 3, 3]])

In [40]:
#Q7 Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type. Also display the table attributes and data types of each column.

import pandas as pd

# Assuming your DataFrame is called 'df' and has a 'Phone' column

# 1. Remove non-numeric characters
#df['Phone'] = df['Phone'].str.replace(r'\D+', '', regex=True)

# 2. Convert to numeric data type
#df['Phone'] = pd.to_numeric(df['Phone'], errors='coerce')

# 3. Display table attributes and data types
#print(df.info())


In [41]:
#Q8 Perform the following tasks using people dataset:

#a) Read the 'data.csv' file using pandas, skipping the first 50 rows.
#df = pd.read_csv('data.csv', skiprows=50)

#b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.
#df = pd.read_csv('data.csv', usecols=['Last Name', 'Gender', 'Email', 'Phone', 'Salary'])

#c)  Display the first 10 rows of the filtered dataset.
#print(df.head(10))

#d) Extract the ‘Salary’' column as a Series and display its last 5 values.
# salary_series = df['Salary']
#last_5_salaries = salary_series.tail(5)





In [42]:
#Q9 Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke', 'Gender' column contains the word Female and ‘Salary’ should be less than 85000.

#filtered_df = People_Dataset[
   # (People_Dataset['Last Name'].str.contains('Duke')) &
    #(People_Dataset['Gender'].str.contains('Female')) &
    #(People_Dataset['Salary'] < 85000)
#]


In [43]:
#Q10 Create a 7*5 Dataframe in Pandas using a series generated from 35 random integers between 1 to 6.

a=pd.Series(np.random.randint(1,6,size=35))
df=pd.DataFrame(a.values.reshape(7,5))
df


0  1  2  3  4
0  1  1  3  4  5
1  5  2  3  3  2
2  4  4  5  2  3
3  4  3  1  3  4
4  5  2  5  3  5
5  5  1  4  4  4
6  3  2  2  1  4

In [44]:
#Q11 Create two different Series, each of length 50, with the following criteria:

#a) The first Series should contain random numbers ranging from 10 to 50.

#b) The second Series should contain random numbers ranging from 100 to 1000.

#c) Create a DataFrame by joining these Series by column, and, change the names of the columns to 'col1', 'col2'.

import random

s1=pd.Series(np.random.randint(10,50,size=50))
s2=pd.Series(np.random.randint(100,1000,size=50))
df=pd.concat([s1,s2],axis=1)
df.columns=['col1','col2']
df


col1  col2
0     47   562
1     43   553
2     48   815
3     39   763
4     27   457
5     22   965
6     26   535
7     14   677
8     32   833
9     20   175
10    37   744
11    10   770
12    16   951
13    49   321
14    12   845
15    49   155
16    39   928
17    13   757
18    14   336
19    31   236
20    24   429
21    31   271
22    30   438
23    35   899
24    39   952
25    47   762
26    13   504
27    32   359
28    16   304
29    44   867
30    47   416
31    39   647
32    13   203
33    45   206
34    37   289
35    49   768
36    46   873
37    44   725
38    46   555
39    28   471
40    35   407
41    41   309
42    19   383
43    32   893
44    10   531
45    39   923
46    17   976
47    10   987
48    18   650
49    42   206

In [45]:
#Q12 Perform the following operations using people data set:

#a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.

#b) Delete the rows containing any missing values.

#c) Print the final output also.

#d1=d1.drop(columns=['Email','Phone','Date of Birth'])
#d1=d1.dropna()
#print(d1)

In [46]:
#Q13 Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the following tasks using Matplotlib and NumPy:

#a) Create a scatter plot using x and y, setting the color of the points to red and the marker style to 'o'.

#b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.

#c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.

#d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.

#e) Set the title of the plot as 'Advanced Scatter Plot of Random Values'.

#f) Display a legend for the scatter plot, the horizontal line, and the vertical line.

''' import numpy as np
import matplotlib.pyplot as plt

# Create NumPy arrays
x = np.random.rand(100)
y = np.random.rand(100)

# a) Scatter plot
plt.scatter(x, y, color='red', marker='o', label='Random Data')

# b) Horizontal line
plt.axhline(y=0.5, linestyle='--', color='blue', label='y = 0.5')

# c) Vertical line
plt.axvline(x=0.5, linestyle=':', color='green', label='x = 0.5')

# d) Axis labels
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# e) Title
plt.title('Advanced Scatter Plot of Random Values')

# f) Legend
plt.legend()

# Display the plot
plt.show() '''

" import numpy as np\nimport matplotlib.pyplot as plt\n\n# Create NumPy arrays\nx = np.random.rand(100)\ny = np.random.rand(100)\n\n# a) Scatter plot\nplt.scatter(x, y, color='red', marker='o', label='Random Data')\n\n# b) Horizontal line\nplt.axhline(y=0.5, linestyle='--', color='blue', label='y = 0.5')\n\n# c) Vertical line\nplt.axvline(x=0.5, linestyle=':', color='green', label='x = 0.5')\n\n# d) Axis labels\nplt.xlabel('X-axis')\nplt.ylabel('Y-axis')\n\n# e) Title\nplt.title('Advanced Scatter Plot of Random Values')\n\n# f) Legend\nplt.legend()\n\n# Display the plot\nplt.show() "

In [47]:
#Q14 Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and Perform the following tasks using Matplotlib:

'''a) Plot the 'Temperature' and 'Humidity' on the same plot with different y-axes (left y-axis for 'Temperature' and
right y-axis for 'Humidity').

b) Label the x-axis as 'Date'.

c) Set the title of the plot as 'Temperature and Humidity Over Time'''

'''import matplotlib.pyplot as plt

# Assuming you have a DataFrame called 'df' with 'Date', 'Temperature', and 'Humidity' columns

# Create the figure and the first axes
fig, ax1 = plt.subplots()

# Plot Temperature on the first axes (left y-axis)
ax1.plot(df['Date'], df['Temperature'], 'b-', label='Temperature')
ax1.set_xlabel('Date')  # Label x-axis
ax1.set_ylabel('Temperature', color='b')  # Label left y-axis
ax1.tick_params('y', labelcolor='b')  # Set tick color for left y-axis

# Create a second axes sharing the same x-axis
ax2 = ax1.twinx()

# Plot Humidity on the second axes (right y-axis)
ax2.plot(df['Date'], df['Humidity'], 'r-', label='Humidity')
ax2.set_ylabel('Humidity', color='r')  # Label right y-axis
ax2.tick_params('y', labelcolor='r')  # Set tick color for right y-axis

# Set the title
plt.title('Temperature and Humidity Over Time')

# Display the plot
plt.show()'''



"import matplotlib.pyplot as plt\n\n# Assuming you have a DataFrame called 'df' with 'Date', 'Temperature', and 'Humidity' columns\n\n# Create the figure and the first axes\nfig, ax1 = plt.subplots()\n\n# Plot Temperature on the first axes (left y-axis)\nax1.plot(df['Date'], df['Temperature'], 'b-', label='Temperature')\nax1.set_xlabel('Date')  # Label x-axis\nax1.set_ylabel('Temperature', color='b')  # Label left y-axis\nax1.tick_params('y', labelcolor='b')  # Set tick color for left y-axis\n\n# Create a second axes sharing the same x-axis\nax2 = ax1.twinx()\n\n# Plot Humidity on the second axes (right y-axis)\nax2.plot(df['Date'], df['Humidity'], 'r-', label='Humidity')\nax2.set_ylabel('Humidity', color='r')  # Label right y-axis\nax2.tick_params('y', labelcolor='r')  # Set tick color for right y-axis\n\n# Set the title\nplt.title('Temperature and Humidity Over Time')\n\n# Display the plot\nplt.show()"

In [48]:
#Q15 Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following tasks using Matplotlib:

'''a) Plot a histogram of the data with 30 bins.

b) Overlay a line plot representing the normal distribution's probability density function (PDF).

c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.

d) Set the title of the plot as 'Histogram with PDF Overlay'.'''

'''import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

# Assuming you have your data in a NumPy array called 'data'

# a) Histogram
plt.hist(data, bins=30, density=True, alpha=0.6, label='Data')

# b) Normal Distribution PDF
mu, std = stats.norm.fit(data)  # Fit a normal distribution to the data
xmin, xmax = plt.xlim()  # Get the x-axis limits
x = np.linspace(xmin, xmax, 100)  # Create a range of x-values
p = stats.norm.pdf(x, mu, std)  # Calculate the PDF values
plt.plot(x, p, 'k', linewidth=2, label='Normal Distribution')

# c) Labels and Title
plt.xlabel('Value')
plt.ylabel('Frequency/Probability')
plt.title('Histogram with PDF Overlay')

# d) Legend
plt.legend()

# Display the plot
plt.show()'''





"import numpy as np\nimport matplotlib.pyplot as plt\nimport scipy.stats as stats\n\n# Assuming you have your data in a NumPy array called 'data'\n\n# a) Histogram\nplt.hist(data, bins=30, density=True, alpha=0.6, label='Data')\n\n# b) Normal Distribution PDF\nmu, std = stats.norm.fit(data)  # Fit a normal distribution to the data\nxmin, xmax = plt.xlim()  # Get the x-axis limits\nx = np.linspace(xmin, xmax, 100)  # Create a range of x-values\np = stats.norm.pdf(x, mu, std)  # Calculate the PDF values\nplt.plot(x, p, 'k', linewidth=2, label='Normal Distribution')\n\n# c) Labels and Title\nplt.xlabel('Value')\nplt.ylabel('Frequency/Probability')\nplt.title('Histogram with PDF Overlay')\n\n# d) Legend\nplt.legend()\n\n# Display the plot\nplt.show()"

In [49]:
#Q16 Set the title of the plot as 'Histogram with PDF Overlay.

# plt.title("Histogram with PDF Overlay")

In [50]:
#Q17 Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot.

'''import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Generate random data
x = np.random.rand(100) - 0.5  # Center around 0
y = np.random.rand(100) - 0.5

# Create quadrant labels
quadrants = []
for i in range(len(x)):
    if x[i] >= 0 and y[i] >= 0:
        quadrants.append('Quadrant I')
    elif x[i] < 0 and y[i] >= 0:
        quadrants.append('Quadrant II')
    elif x[i] < 0 and y[i] < 0:
        quadrants.append('Quadrant III')
    else:
        quadrants.append('Quadrant IV')

# Create Seaborn scatter plot
sns.scatterplot(x=x, y=y, hue=quadrants, palette='viridis')

# Customize the plot
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Quadrant-wise Scatter Plot')
plt.legend(title='Quadrants')

# Display the plot
plt.show()'''



"import numpy as np\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\n# Generate random data\nx = np.random.rand(100) - 0.5  # Center around 0\ny = np.random.rand(100) - 0.5\n\n# Create quadrant labels\nquadrants = []\nfor i in range(len(x)):\n    if x[i] >= 0 and y[i] >= 0:\n        quadrants.append('Quadrant I')\n    elif x[i] < 0 and y[i] >= 0:\n        quadrants.append('Quadrant II')\n    elif x[i] < 0 and y[i] < 0:\n        quadrants.append('Quadrant III')\n    else:\n        quadrants.append('Quadrant IV')\n\n# Create Seaborn scatter plot\nsns.scatterplot(x=x, y=y, hue=quadrants, palette='viridis')\n\n# Customize the plot\nplt.xlabel('X-axis')\nplt.ylabel('Y-axis')\nplt.title('Quadrant-wise Scatter Plot')\nplt.legend(title='Quadrants')\n\n# Display the plot\nplt.show()"

In [51]:
#Q18 With Bokeh, plot a line chart of a sine wave function, add grid lines, label the axes, and set the title as 'Sine Wave Function'.

'''from bokeh.plotting import figure, show
import numpy as np

# Generate data
x = np.linspace(0, 4*np.pi, 100)
y = np.sin(x)

# Create a Bokeh figure
p = figure(title="Sine Wave Function", x_axis_label='x', y_axis_label='sin(x)')

# Add line plot
p.line(x, y, line_width=2)

# Add grid lines
p.xgrid.grid_line_color = "gray"
p.ygrid.grid_line_color = "gray"

# Show the plot
show(p)'''


'from bokeh.plotting import figure, show\nimport numpy as np\n\n# Generate data\nx = np.linspace(0, 4*np.pi, 100)\ny = np.sin(x)\n\n# Create a Bokeh figure\np = figure(title="Sine Wave Function", x_axis_label=\'x\', y_axis_label=\'sin(x)\')\n\n# Add line plot\np.line(x, y, line_width=2)\n\n# Add grid lines\np.xgrid.grid_line_color = "gray"\np.ygrid.grid_line_color = "gray"\n\n# Show the plot\nshow(p)'

In [52]:
#Q19 Using Bokeh, generate a bar chart of randomly generated categorical data, color bars based on their values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Categorical Bar Chart'8.

'''import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.transform import factor_cmap

# Generate categorical data
categories = ['A', 'B', 'C', 'D', 'E']
counts = np.random.randint(1, 11, size=5)  # Random counts for each category

# Create data source
source = ColumnDataSource(data=dict(categories=categories, counts=counts))

# Create color map
color_map = factor_cmap('categories', palette=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'],
                        factors=categories)

# Create figure
p = figure(x_range=categories, title="Random Categorical Bar Chart",
           x_axis_label="Categories", y_axis_label="Counts")

# Add bar plot
p.vbar(x='categories', top='counts', width=0.9, source=source,
       color=color_map, legend_field="categories")

# Add hover tooltips
hover = HoverTool(tooltips=[("Category", "@categories"), ("Count", "@counts")])
p.add_tools(hover)

# Customize legend
p.legend.orientation = "horizontal"
p.legend.location = "top_center"

# Show the plot
show(p)'''



'import numpy as np\nfrom bokeh.plotting import figure, show\nfrom bokeh.models import ColumnDataSource, HoverTool\nfrom bokeh.transform import factor_cmap\n\n# Generate categorical data\ncategories = [\'A\', \'B\', \'C\', \'D\', \'E\']\ncounts = np.random.randint(1, 11, size=5)  # Random counts for each category\n\n# Create data source\nsource = ColumnDataSource(data=dict(categories=categories, counts=counts))\n\n# Create color map\ncolor_map = factor_cmap(\'categories\', palette=[\'#1f77b4\', \'#ff7f0e\', \'#2ca02c\', \'#d62728\', \'#9467bd\'], \n                        factors=categories)\n\n# Create figure\np = figure(x_range=categories, title="Random Categorical Bar Chart", \n           x_axis_label="Categories", y_axis_label="Counts")\n\n# Add bar plot\np.vbar(x=\'categories\', top=\'counts\', width=0.9, source=source, \n       color=color_map, legend_field="categories")\n\n# Add hover tooltips\nhover = HoverTool(tooltips=[("Category", "@categories"), ("Count", "@counts")])\np.ad

In [53]:
#Q20 Using Plotly, create a basic line plot of a randomly generated dataset, label the axes, and set the title as 'Simple Line Plot'.

'''import plotly.graph_objects as go
import numpy as np

# Generate random data
x = np.arange(10)
y = np.random.rand(10)

# Create the figure
fig = go.Figure(data=go.Scatter(x=x, y=y, mode='lines'))

# Update layout with labels and title
fig.update_layout(
    title="Simple Line Plot",
    xaxis_title="X-axis",
    yaxis_title="Y-axis"
)

# Show the plot
fig.show()'''


'import plotly.graph_objects as go\nimport numpy as np\n\n# Generate random data\nx = np.arange(10)\ny = np.random.rand(10)\n\n# Create the figure\nfig = go.Figure(data=go.Scatter(x=x, y=y, mode=\'lines\'))\n\n# Update layout with labels and title\nfig.update_layout(\n    title="Simple Line Plot",\n    xaxis_title="X-axis",\n    yaxis_title="Y-axis"\n)\n\n# Show the plot\nfig.show()'

In [54]:
#Q21 Using Plotly, create an interactive pie chart of randomly generated data, add labels and percentages, set the title as 'Interactive Pie Chart'.

'''import plotly.express as px
import numpy as np

# Generate random data
labels = ['Category A', 'Category B', 'Category C', 'Category D', 'Category E']
values = np.random.randint(1, 11, size=5)

# Create the pie chart
fig = px.pie(values=values, names=labels, title='Interactive Pie Chart')

# Update layout for percentages and hover information
fig.update_traces(textinfo='percent+label', hoverinfo='label+percent+value')

# Show the plot
fig.show()'''



"import plotly.express as px\nimport numpy as np\n\n# Generate random data\nlabels = ['Category A', 'Category B', 'Category C', 'Category D', 'Category E']\nvalues = np.random.randint(1, 11, size=5)\n\n# Create the pie chart\nfig = px.pie(values=values, names=labels, title='Interactive Pie Chart')\n\n# Update layout for percentages and hover information\nfig.update_traces(textinfo='percent+label', hoverinfo='label+percent+value')\n\n# Show the plot\nfig.show()"