In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
np.__version__

'1.19.2'

In [4]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://www.scipy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as `np`::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide a

In [5]:
l=[1,2,3,4]
arr=np.array(l)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(4,)

In [10]:
arr.size

4

In [11]:
arr.ndim

1

In [12]:
mat=np.matrix(l) #matrix formation

In [13]:
mat

matrix([[1, 2, 3, 4]])

In [14]:
type(mat)

numpy.matrix

In [15]:
mat.ndim

2

In [16]:
mat.shape

(1, 4)

In [17]:
mat.size

4

In [18]:
arr1=np.asarray(l)
arr1

array([1, 2, 3, 4])

In [19]:
t=([1,2,3,4],[8,9])
type(t)

tuple

In [20]:
arr2=np.asarray(t)
arr2

/Users/apple/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


array([list([1, 2, 3, 4]), list([8, 9])], dtype=object)

In [21]:
arr1[0]

1

In [22]:
arr1[3]

4

In [23]:
arr3=arr1.copy()

In [24]:
arr3

array([1, 2, 3, 4])

In [25]:
arr3[2]=5

In [26]:
arr3

array([1, 2, 5, 4])

In [27]:
arr1

array([1, 2, 3, 4])

In [28]:
arr=np.fromfunction(lambda i,j:i*j,(3,3)) #indices multiplication

In [29]:
arr

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
arr[2][1]

2.0

In [35]:
it=[i for i in range(10)]
it

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
a=np.fromiter(it,float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
b=np.fromstring('98 54 78',sep=" ",dtype=int)
b

array([98, 54, 78])

In [40]:
b=np.fromstring('98 54 78',sep=" ") #bydefaultfloat
b

array([98., 54., 78.])

In [41]:
s="Mayank Kumar Mishra"
s.split(",")

['Mayank Kumar Mishra']

In [42]:
s[1]

'a'

In [43]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
np.arange(15,2) #empty array

array([], dtype=int64)

In [46]:
np.arange(1,100,15)

array([ 1, 16, 31, 46, 61, 76, 91])

In [47]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [49]:
np.arange(1,4,0.3)

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7])

In [50]:
a=np.zeros(5)

In [51]:
a

array([0., 0., 0., 0., 0.])

In [53]:
b=np.zeros((4,5),dtype=int)
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [54]:
c=np.ones((10,20),dtype=int)
c

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [56]:
d=np.zeros((3,4,6)) #3D array...4x6 array repeated 3 times
d

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [57]:
d.ndim

3

In [58]:
d.size

72

In [59]:
d.shape

(3, 4, 6)

In [60]:
e=np.array([[1,4,7],[2,6,9],[3,5,8]])
e

array([[1, 4, 7],
       [2, 6, 9],
       [3, 5, 8]])

In [61]:
e+2

array([[ 3,  6,  9],
       [ 4,  8, 11],
       [ 5,  7, 10]])

In [62]:
e-9

array([[-8, -5, -2],
       [-7, -3,  0],
       [-6, -4, -1]])

In [63]:
e*4

array([[ 4, 16, 28],
       [ 8, 24, 36],
       [12, 20, 32]])

In [64]:
e/6

array([[0.16666667, 0.66666667, 1.16666667],
       [0.33333333, 1.        , 1.5       ],
       [0.5       , 0.83333333, 1.33333333]])

In [65]:
e**2

array([[ 1, 16, 49],
       [ 4, 36, 81],
       [ 9, 25, 64]])

In [66]:
f=np.array([[100,232,678],[436,792,122],[368,802,321]])
f

array([[100, 232, 678],
       [436, 792, 122],
       [368, 802, 321]])

In [68]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [70]:
f.T

array([[100, 436, 368],
       [232, 792, 802],
       [678, 122, 321]])

In [71]:
e.T

array([[1, 2, 3],
       [4, 6, 5],
       [7, 9, 8]])

In [72]:
f.reshape(9,1)

array([[100],
       [232],
       [678],
       [436],
       [792],
       [122],
       [368],
       [802],
       [321]])

In [73]:
f.reshape(1,9)

array([[100, 232, 678, 436, 792, 122, 368, 802, 321]])

In [74]:
import random

In [76]:
random.choice((1,2,3,4,5)) #any random value will get return

3

In [77]:
random.choice((1,2,3,4,5))

1

In [78]:
random.choice("Mayank")

'k'

In [79]:
random.randrange(2,26)

16

In [81]:
random.choice("Mayank")

'n'

In [82]:
random.randrange(2,26)

3

In [83]:
random.random() #any random number between 0(included) and 1(excluded) will produce

0.9550463115307891

In [84]:
l1=[21,34,78,56]
random.shuffle(l1)

In [85]:
random.shuffle(l1)

In [86]:
l1

[21, 34, 56, 78]

In [88]:
random.shuffle(l1)
l1

[21, 34, 78, 56]

In [89]:
random.uniform(7,14) #any random number will generate

13.007737581865307

In [90]:
random.uniform(8,12)

10.242091547721577

In [91]:
np.random.rand(2,3) #random array

array([[0.32393995, 0.49318183, 0.91901633],
       [0.4681119 , 0.53859896, 0.34491446]])

In [92]:
np.random.randn() #value from normal distribution curve

0.9248634039795588

In [93]:
e.reshape(9,-1) #dont know reshaping value then use -1

array([[1],
       [4],
       [7],
       [2],
       [6],
       [9],
       [3],
       [5],
       [8]])

In [94]:
f.reshape(-1,9)

array([[100, 232, 678, 436, 792, 122, 368, 802, 321]])

In [97]:
ar=np.random.randint(1,10,(4,5))
ar

array([[7, 3, 4, 1, 8],
       [2, 9, 6, 2, 5],
       [9, 6, 4, 9, 4],
       [4, 6, 7, 7, 6]])

In [98]:
ar>6 #return conditions

array([[ True, False, False, False,  True],
       [False,  True, False, False, False],
       [ True, False, False,  True, False],
       [False, False,  True,  True, False]])

In [99]:
ar[ar>6] #return values

array([7, 8, 9, 9, 9, 7, 7])

In [100]:
ar[ar<8]

array([7, 3, 4, 1, 2, 6, 2, 5, 6, 4, 4, 4, 6, 7, 7, 6])

In [101]:
ar[2][3]

9

In [102]:
ar[1][2]

6

In [103]:
ar[0:3,1:3] #row and column axis

array([[3, 4],
       [9, 6],
       [6, 4]])

In [104]:
ar[1:4]

array([[2, 9, 6, 2, 5],
       [9, 6, 4, 9, 4],
       [4, 6, 7, 7, 6]])

In [105]:
ar[0:3,[0,2]]

array([[7, 4],
       [2, 6],
       [9, 4]])

In [106]:
ar[0,[1,3]]

array([3, 1])

In [107]:
e+f

array([[101, 236, 685],
       [438, 798, 131],
       [371, 807, 329]])

In [108]:
e-f

array([[ -99, -228, -671],
       [-434, -786, -113],
       [-365, -797, -313]])

In [109]:
e/f

array([[0.01      , 0.01724138, 0.01032448],
       [0.00458716, 0.00757576, 0.07377049],
       [0.00815217, 0.00623441, 0.02492212]])

In [110]:
e*f #index multiplication

array([[ 100,  928, 4746],
       [ 872, 4752, 1098],
       [1104, 4010, 2568]])

In [111]:
e@f #matrix multiplication

array([[ 4420,  9014,  3413],
       [ 6128, 12434,  4977],
       [ 5424, 11072,  5212]])

In [112]:
np.dot(e,f) #matrix multiplication

array([[ 4420,  9014,  3413],
       [ 6128, 12434,  4977],
       [ 5424, 11072,  5212]])

In [113]:
f/0

<ipython-input-113-0ac64f883b84>:1: RuntimeWarning: divide by zero encountered in true_divide
  f/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [114]:
f.flatten() #convert multidimensional array to 1D array

array([100, 232, 678, 436, 792, 122, 368, 802, 321])

In [116]:
np.expand_dims(e,axis=0)

array([[[1, 4, 7],
        [2, 6, 9],
        [3, 5, 8]]])

In [117]:
np.expand_dims(e,axis=1)

array([[[1, 4, 7]],

       [[2, 6, 9]],

       [[3, 5, 8]]])

In [118]:
np.squeeze(f)

array([[100, 232, 678],
       [436, 792, 122],
       [368, 802, 321]])

In [119]:
np.repeat(f,3)

array([100, 100, 100, 232, 232, 232, 678, 678, 678, 436, 436, 436, 792,
       792, 792, 122, 122, 122, 368, 368, 368, 802, 802, 802, 321, 321,
       321])

In [120]:
np.roll(e,-1)

array([[4, 7, 2],
       [6, 9, 3],
       [5, 8, 1]])

In [121]:
np.roll(f,2)

array([[802, 321, 100],
       [232, 678, 436],
       [792, 122, 368]])

In [122]:
~f #bitwise operator: negative the value and reduce by -1

array([[-101, -233, -679],
       [-437, -793, -123],
       [-369, -803, -322]])

In [123]:
g=np.array(['train'])
g

array(['train'], dtype='<U5')

In [124]:
np.char.upper(g)

array(['TRAIN'], dtype='<U5')

In [125]:
np.char.capitalize(g)

array(['Train'], dtype='<U5')

In [126]:
np.exp(e)

array([[2.71828183e+00, 5.45981500e+01, 1.09663316e+03],
       [7.38905610e+00, 4.03428793e+02, 8.10308393e+03],
       [2.00855369e+01, 1.48413159e+02, 2.98095799e+03]])

In [127]:
np.log10(e)

array([[0.        , 0.60205999, 0.84509804],
       [0.30103   , 0.77815125, 0.95424251],
       [0.47712125, 0.69897   , 0.90308999]])

In [128]:
np.extract(e>3,e)

array([4, 7, 6, 9, 5, 8])

In [129]:
e[e>3]

array([4, 7, 6, 9, 5, 8])

In [130]:
np.linalg.det(e) #determinant

-9.000000000000005

In [131]:
np.linalg.inv(f) #inverse

array([[ 0.0047311 ,  0.01419692, -0.0153885 ],
       [-0.00287578, -0.00657697,  0.00857375],
       [ 0.00176117,  0.00015659, -0.0006641 ]])

In [132]:
np.linalg.solve(e,f) #linearequations

array([[  66.66666667,  193.33333333,  -52.66666667],
       [ 303.11111111,  414.88888889, -830.77777778],
       [-168.44444444, -231.55555556,  579.11111111]])

In [133]:
np.sqrt(l)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [136]:
np.subtract(f,e)

array([[ 99, 228, 671],
       [434, 786, 113],
       [365, 797, 313]])

In [137]:
import numpy.matlib as nm #module for matrix

In [138]:
nm.zeros(4)

matrix([[0., 0., 0., 0.]])

In [139]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [140]:
nm.ones((2,3))

matrix([[1., 1., 1.],
        [1., 1., 1.]])

In [146]:
s=pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [143]:
s[3]

4

In [144]:
s.reset_index(drop=True)

0    1
1    2
2    3
3    4
dtype: int64

In [145]:
s1=pd.Series([1,2,3],index=['a','b','c'])
s1

a    1
b    2
c    3
dtype: int64

In [147]:
s1.reset_index(drop=True)

0    1
1    2
2    3
dtype: int64

In [148]:
s1.index

Index(['a', 'b', 'c'], dtype='object')

In [149]:
df=pd.DataFrame({'Country':['India','Usa','Australia','Nz'],'Capital':['New Delhi','WashingtonDC','Canberra','Wellington'],'Area':[3.287,9.834,7.741,0.268],'Code':['Ind','USA',None,None]})
df

Country       Capital   Area  Code
0      India     New Delhi  3.287   Ind
1        Usa  WashingtonDC  9.834   USA
2  Australia      Canberra  7.741  None
3         Nz    Wellington  0.268  None

In [150]:
df.head(2)

Country       Capital   Area Code
0   India     New Delhi  3.287  Ind
1     Usa  WashingtonDC  9.834  USA

In [151]:
df.tail(2)

Country     Capital   Area  Code
2  Australia    Canberra  7.741  None
3         Nz  Wellington  0.268  None

In [152]:
df.shape

(4, 4)

In [153]:
df.columns

Index(['Country', 'Capital', 'Area', 'Code'], dtype='object')

In [154]:
df.sample() #random value

Country     Capital   Area  Code
3      Nz  Wellington  0.268  None

In [155]:
df.sample()

Country   Capital   Area  Code
2  Australia  Canberra  7.741  None

In [156]:
df.dtypes

Country     object
Capital     object
Area       float64
Code        object
dtype: object

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Country  4 non-null      object 
 1   Capital  4 non-null      object 
 2   Area     4 non-null      float64
 3   Code     2 non-null      object 
dtypes: float64(1), object(3)
memory usage: 256.0+ bytes


In [158]:
df.describe

<bound method NDFrame.describe of      Country       Capital   Area  Code
0      India     New Delhi  3.287   Ind
1        Usa  WashingtonDC  9.834   USA
2  Australia      Canberra  7.741  None
3         Nz    Wellington  0.268  None>

In [159]:
df['Code']

0     Ind
1     USA
2    None
3    None
Name: Code, dtype: object

In [160]:
df['Temp']=[45,43,28,22] #new column 

In [161]:
df

Country       Capital   Area  Code  Temp
0      India     New Delhi  3.287   Ind    45
1        Usa  WashingtonDC  9.834   USA    43
2  Australia      Canberra  7.741  None    28
3         Nz    Wellington  0.268  None    22

In [162]:
df[['Country','Capital']] #two col access

Country       Capital
0      India     New Delhi
1        Usa  WashingtonDC
2  Australia      Canberra
3         Nz    Wellington

In [163]:
df.columns

Index(['Country', 'Capital', 'Area', 'Code', 'Temp'], dtype='object')

In [164]:
df[0:2] #row access

Country       Capital   Area Code  Temp
0   India     New Delhi  3.287  Ind    45
1     Usa  WashingtonDC  9.834  USA    43

In [165]:
df['Capital'].unique() #unique values

array(['New Delhi', 'WashingtonDC', 'Canberra', 'Wellington'],
      dtype=object)

In [166]:
df['Capital'].nunique() #number of unique values

4

In [167]:
df['Capital'].value_counts()

WashingtonDC    1
Canberra        1
New Delhi       1
Wellington      1
Name: Capital, dtype: int64

In [168]:
df['Capital'].value_counts(normalize=True) #percentage value

WashingtonDC    0.25
Canberra        0.25
New Delhi       0.25
Wellington      0.25
Name: Capital, dtype: float64

In [169]:
df['Temp']<33

0    False
1    False
2     True
3     True
Name: Temp, dtype: bool

In [170]:
df[df['Temp']<33]

Country     Capital   Area  Code  Temp
2  Australia    Canberra  7.741  None    28
3         Nz  Wellington  0.268  None    22

In [171]:
df.iloc[1:3] #row access

Country       Capital   Area  Code  Temp
1        Usa  WashingtonDC  9.834   USA    43
2  Australia      Canberra  7.741  None    28

In [174]:
df.loc[0:2,['Temp','Country']] # 0 to 2 and all three values are included

Temp    Country
0    45      India
1    43        Usa
2    28  Australia

In [175]:
df.iloc[1:3,0:2]

Country       Capital
1        Usa  WashingtonDC
2  Australia      Canberra

In [176]:
df.drop('Temp',inplace=True)

KeyError: "['Temp'] not found in axis"

In [177]:
df.drop('Temp',axis=1) #deleting col

Country       Capital   Area  Code
0      India     New Delhi  3.287   Ind
1        Usa  WashingtonDC  9.834   USA
2  Australia      Canberra  7.741  None
3         Nz    Wellington  0.268  None

In [178]:
df.drop(1,axis=0) #deleting row

Country     Capital   Area  Code  Temp
0      India   New Delhi  3.287   Ind    45
2  Australia    Canberra  7.741  None    28
3         Nz  Wellington  0.268  None    22

In [179]:
df.isnull()

Country  Capital   Area   Code   Temp
0    False    False  False  False  False
1    False    False  False  False  False
2    False    False  False   True  False
3    False    False  False   True  False

In [180]:
df.isnull().sum() #sum of null values

Country    0
Capital    0
Area       0
Code       2
Temp       0
dtype: int64

In [181]:
df.dropna()

Country       Capital   Area Code  Temp
0   India     New Delhi  3.287  Ind    45
1     Usa  WashingtonDC  9.834  USA    43

In [182]:
df.fillna('404')

Country       Capital   Area Code  Temp
0      India     New Delhi  3.287  Ind    45
1        Usa  WashingtonDC  9.834  USA    43
2  Australia      Canberra  7.741  404    28
3         Nz    Wellington  0.268  404    22

In [183]:
df.fillna(404)

Country       Capital   Area Code  Temp
0      India     New Delhi  3.287  Ind    45
1        Usa  WashingtonDC  9.834  USA    43
2  Australia      Canberra  7.741  404    28
3         Nz    Wellington  0.268  404    22

In [184]:
df['Temp'].mean()

34.5

In [185]:
df['Temp'].sum()

138

In [186]:
df['Temp'].var()

127.0

In [187]:
df['Temp'].max()

45

In [188]:
df.fillna(method='ffill')

Country       Capital   Area Code  Temp
0      India     New Delhi  3.287  Ind    45
1        Usa  WashingtonDC  9.834  USA    43
2  Australia      Canberra  7.741  USA    28
3         Nz    Wellington  0.268  USA    22

In [189]:
df.fillna(method='bfill')

Country       Capital   Area  Code  Temp
0      India     New Delhi  3.287   Ind    45
1        Usa  WashingtonDC  9.834   USA    43
2  Australia      Canberra  7.741  None    28
3         Nz    Wellington  0.268  None    22

In [190]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [191]:
df.std()

Area     4.316156
Temp    11.269428
dtype: float64

In [192]:
def convt(x):
    return x*90
df['Area'].apply(convt) #function apply to df

0    295.83
1    885.06
2    696.69
3     24.12
Name: Area, dtype: float64

In [194]:
df.reindex(['I','II','III','IV']) #new index creation

Country Capital  Area Code  Temp
I       NaN     NaN   NaN  NaN   NaN
II      NaN     NaN   NaN  NaN   NaN
III     NaN     NaN   NaN  NaN   NaN
IV      NaN     NaN   NaN  NaN   NaN

In [195]:
df.sort_values(by='Country') #sorting, by default asc ordera[]

Country       Capital   Area  Code  Temp
2  Australia      Canberra  7.741  None    28
0      India     New Delhi  3.287   Ind    45
3         Nz    Wellington  0.268  None    22
1        Usa  WashingtonDC  9.834   USA    43

In [196]:
df['Capital'].str.upper()

0       NEW DELHI
1    WASHINGTONDC
2        CANBERRA
3      WELLINGTON
Name: Capital, dtype: object

In [197]:
df.rolling(window=2).mean()

Area  Temp
0     NaN   NaN
1  6.5605  44.0
2  8.7875  35.5
3  4.0045  25.0

In [199]:
df.Temp.cumsum()

0     45
1     88
2    116
3    138
Name: Temp, dtype: int64

In [204]:
df['Area'].astype(int)

0    3
1    9
2    7
3    0
Name: Area, dtype: int64

In [206]:
df['Country'][1].startswith('U')

True

In [207]:
import time

In [208]:
s=time.time()

In [209]:
s

1730907888.002364

In [211]:
pip install yfinance

     |████████████████████████████████| 101 kB 961 kB/s ta 0:00:01
     |████████████████████████████████| 4.5 MB 1.4 MB/s eta 0:00:01
     |████████████████████████████████| 64 kB 1.5 MB/s eta 0:00:01
     |████████████████████████████████| 939 kB 2.6 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 508 kB 2.0 MB/s eta 0:00:01
     |████████████████████████████████| 11.7 MB 1.9 MB/s eta 0:00:01
     |████████████████████████████████| 147 kB 1.5 MB/s eta 0:00:01
     |████████████████████████████████| 124 kB 2.2 MB/s eta 0:00:01
     |████████████████████████████████| 229 kB 2.8 MB/s eta 0:00:01    |███████▏                        | 51 kB 2.2 MB/s eta 0:00:01     |███████████████████████████████▍| 225 kB 2.8 MB/s eta 0:00:01
     |████████████████████████████████| 346 kB 2.5 MB/s eta 0:00:01
  Created wheel for peewee: filename=peewee-3.17.7-py3-none-any

In [212]:
import yfinance as yf #yahoo finance

In [213]:
df1=yf.download('GOOG',start='2023-05-16',end='2024-02-26')

[*********************100%***********************]  1 of 1 completed


In [214]:
df1

Price                       Adj Close       Close        High         Low  \
Ticker                           GOOG        GOOG        GOOG        GOOG   
Date                                                                        
2023-05-16 00:00:00+00:00  119.795799  120.089996  121.199997  116.830002   
2023-05-17 00:00:00+00:00  121.182396  121.480003  122.279999  119.459999   
2023-05-18 00:00:00+00:00  123.217392  123.519997  123.900002  121.489998   
2023-05-19 00:00:00+00:00  122.948067  123.250000  126.478996  122.720001   
2023-05-22 00:00:00+00:00  125.561646  125.870003  127.050003  123.449997   
...                               ...         ...         ...         ...   
2024-02-16 00:00:00+00:00  141.412704  141.759995  144.479996  141.520004   
2024-02-20 00:00:00+00:00  141.851639  142.199997  143.328995  140.800003   
2024-02-21 00:00:00+00:00  143.487610  143.839996  143.979996  141.910004   
2024-02-22 00:00:00+00:00  144.964005  145.320007  146.199997  144.009995   
2024-02-23 00:00:00+00:00  144.934067  145.289993  145.955002  144.789993   

Price                            Open    Volume  
Ticker                           GOOG      GOOG  
Date                                             
2023-05-16 00:00:00+00:00  116.830002  32370100  
2023-05-17 00:00:00+00:00  120.180000  26659600  
2023-05-18 00:00:00+00:00  121.559998  27014500  
2023-05-19 00:00:00+00:00  124.199997  30251300  
2023-05-22 00:00:00+00:00  123.510002  29760200  
...                               ...       ...  
2024-02-16 00:00:00+00:00  144.210007  21849700  
2024-02-20 00:00:00+00:00  140.940002  18625600  
2024-02-21 00:00:00+00:00  142.639999  16499600  
2024-02-22 00:00:00+00:00  146.119995  23024700  
2024-02-23 00:00:00+00:00  144.970001  14519400  

[195 rows x 6 columns]

In [215]:
df1=yf.download('TSLA',start='2024-01-16',end='2024-02-26')

[*********************100%***********************]  1 of 1 completed


In [216]:
df1

Price                       Adj Close       Close        High         Low  \
Ticker                           TSLA        TSLA        TSLA        TSLA   
Date                                                                        
2024-01-16 00:00:00+00:00  219.910004  219.910004  223.490005  212.179993   
2024-01-17 00:00:00+00:00  215.550003  215.550003  215.669998  212.009995   
2024-01-18 00:00:00+00:00  211.880005  211.880005  217.449997  208.740005   
2024-01-19 00:00:00+00:00  212.190002  212.190002  213.190002  207.559998   
2024-01-22 00:00:00+00:00  208.800003  208.800003  217.800003  206.270004   
2024-01-23 00:00:00+00:00  209.139999  209.139999  215.649994  207.750000   
2024-01-24 00:00:00+00:00  207.830002  207.830002  212.729996  206.770004   
2024-01-25 00:00:00+00:00  182.630005  182.630005  193.000000  180.059998   
2024-01-26 00:00:00+00:00  183.250000  183.250000  186.779999  182.100006   
2024-01-29 00:00:00+00:00  190.929993  190.929993  191.479996  183.669998   
2024-01-30 00:00:00+00:00  191.589996  191.589996  196.360001  190.610001   
2024-01-31 00:00:00+00:00  187.289993  187.289993  193.970001  185.850006   
2024-02-01 00:00:00+00:00  188.860001  188.860001  189.880005  184.279999   
2024-02-02 00:00:00+00:00  187.910004  187.910004  188.690002  182.000000   
2024-02-05 00:00:00+00:00  181.059998  181.059998  184.679993  175.009995   
2024-02-06 00:00:00+00:00  185.100006  185.100006  186.490005  177.110001   
2024-02-07 00:00:00+00:00  187.580002  187.580002  189.789993  182.679993   
2024-02-08 00:00:00+00:00  189.559998  189.559998  191.619995  185.580002   
2024-02-09 00:00:00+00:00  193.570007  193.570007  194.119995  189.479996   
2024-02-12 00:00:00+00:00  188.130005  188.130005  194.729996  187.279999   
2024-02-13 00:00:00+00:00  184.020004  184.020004  187.259995  182.110001   
2024-02-14 00:00:00+00:00  188.710007  188.710007  188.889999  183.350006   
2024-02-15 00:00:00+00:00  200.449997  200.449997  200.880005  188.860001   
2024-02-16 00:00:00+00:00  199.949997  199.949997  203.169998  197.399994   
2024-02-20 00:00:00+00:00  193.759995  193.759995  198.600006  189.130005   
2024-02-21 00:00:00+00:00  194.770004  194.770004  199.440002  191.949997   
2024-02-22 00:00:00+00:00  197.410004  197.410004  198.320007  191.360001   
2024-02-23 00:00:00+00:00  191.970001  191.970001  197.570007  191.500000   

Price                            Open     Volume  
Ticker                           TSLA       TSLA  
Date                                              
2024-01-16 00:00:00+00:00  215.100006  115355000  
2024-01-17 00:00:00+00:00  214.860001  103164400  
2024-01-18 00:00:00+00:00  216.880005  108595400  
2024-01-19 00:00:00+00:00  209.990005  102095800  
2024-01-22 00:00:00+00:00  212.259995  117952500  
2024-01-23 00:00:00+00:00  211.300003  106605900  
2024-01-24 00:00:00+00:00  211.880005  123369900  
2024-01-25 00:00:00+00:00  189.699997  198076800  
2024-01-26 00:00:00+00:00  185.500000  107343200  
2024-01-29 00:00:00+00:00  185.630005  125013100  
2024-01-30 00:00:00+00:00  195.330002  109982300  
2024-01-31 00:00:00+00:00  187.000000  103221400  
2024-02-01 00:00:00+00:00  188.500000   91843300  
2024-02-02 00:00:00+00:00  185.039993  110505100  
2024-02-05 00:00:00+00:00  184.259995  134294400  
2024-02-06 00:00:00+00:00  177.210007  122676000  
2024-02-07 00:00:00+00:00  188.179993  111535200  
2024-02-08 00:00:00+00:00  189.000000   83034000  
2024-02-09 00:00:00+00:00  190.179993   84476300  
2024-02-12 00:00:00+00:00  192.110001   95498600  
2024-02-13 00:00:00+00:00  183.990005   86759500  
2024-02-14 00:00:00+00:00  185.300003   81203000  
2024-02-15 00:00:00+00:00  189.160004  120831800  
2024-02-16 00:00:00+00:00  202.059998  111173600  
2024-02-20 00:00:00+00:00  196.130005  104545800  
2024-02-21 00:00:00+00:00  193.360001  103844000  
2024-02-22 00:00:00+00:00  194.000000   92739500  
2024-02-23 00:00:00+00:00  195.309998   78841900

In [218]:
print('coding over')

coding over
